name: app_updater_flutter
description: A robust, modular update checker for Flutter. Supports Android (Play Store) & iOS (App Store) with native UI, scraping fallback, and custom JSON sources.
repository: https://github.com/KarthikManikuttan/app_updater_flutter.git
version: 1.0.0

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  in_app_update: ^4.2.5
  package_info_plus: ^9.0.0
  pub_semver: ^2.2.0
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

topics:
  - flutter
  - update
  - store
  - android
  - ios
  - app-store
  - play-store
  - in-app-update
  - package-info-plus
  - pub-semver
  - shared-preferences
  - url-launcher

platforms:
  android: 
  ios: 

lisence: MIT